services:
  - type: web
    name: todo-fastapi-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-fastapi-db
          property: connectionString